const KEY='sea-portfolio-content';let data=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(window.SEA_DEFAULT),current='profile';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>{current=x.dataset.tab;document.querySelectorAll('.tab').forEach(y=>y.classList.toggle('active',y===x));renderEditor()});
const field=(label,path,value,wide=false)=>`<div class="field ${wide?'wide':''}"><label>${label}<input data-path="${path}" value="${esc(value)}"></label></div>`;
const text=(label,path,value)=>`<div class="field"><label>${label}<textarea data-path="${path}">${esc(value)}</textarea></label></div>`;
function section(title,desc,content){return `<div class="form-section"><h2>${title}</h2><p>${desc}</p>${content}</div>`}
function renderEditor(){let html='',title='';if(current==='profile'){title='Profil & iletişim';const p=data.profile;html=section('Kimlik','Ana sayfada gösterilen genel bilgiler.',`<div class="grid">${field('Ad soyad','profile.name',p.name)}${field('Kısa logo','profile.initials',p.initials)}${field('Türkçe unvan','profile.role.tr',p.role.tr)}${field('English title','profile.role.en',p.role.en)}</div>${text('Türkçe tanıtım','profile.intro.tr',p.intro.tr)}${text('English introduction','profile.intro.en',p.intro.en)}`)+section('Görseller ve iletişim','Görsel yolu yerel bir dosya veya HTTPS bağlantısı olabilir.',`<div class="grid">${field('Profil fotoğrafı yolu','profile.photo',p.photo)}${field('Logo yolu','profile.logo',p.logo)}${field('E-posta','profile.email',p.email)}${field('Alternatif e-posta','profile.alternateEmail',p.alternateEmail)}${field('GitHub kullanıcı adı','profile.github',p.github)}</div><p class="hint">Görselleri assets klasörüne koyup örn. assets/yeni-foto.jpg yazabilirsiniz.</p>`)}
if(current==='about'){title='Hakkımda';html=section('Türkçe','Portföydeki Hakkımda metni.',text('Paragraf 1','about.tr.0',data.about.tr[0])+text('Paragraf 2','about.tr.1',data.about.tr[1]))+section('English', 'About section in English.',text('Paragraph 1','about.en.0',data.about.en[0])+text('Paragraph 2','about.en.1',data.about.en[1]));}
if(current==='skills'){title='Yetenekler';html=section('Teknolojiler','Virgülle ayırarak düzenleyin.',text('Teknoloji listesi','skills',data.skills.join(', ')));}
if(current==='projects'){title='Projeler';html=section('Proje kartları','Kartlar aşağıdaki sırayla yayınlanır.',data.projects.map((p,i)=>`<div class="project-card"><div class="card-title">Proje ${i+1}<button class="remove" data-remove-project="${i}">Sil</button></div><div class="grid">${field('Başlık (TR)','projects.'+i+'.name.tr',typeof p.name==='string'?p.name:p.name.tr)}${field('Title (EN)','projects.'+i+'.name.en',typeof p.name==='string'?p.name:p.name.en)}${field('Simge veya görsel yolu','projects.'+i+'.icon',p.icon)}${field('Teknolojiler (virgüllü)','projects.'+i+'.tech',p.tech.join(', '))}</div>${text('Açıklama (TR)','projects.'+i+'.tr',p.tr)}${text('Description (EN)','projects.'+i+'.en',p.en)}</div>`).join('')+'<button class="add" data-add-project>+ Proje ekle</button>');}
if(current==='timeline'){title='Deneyim & eğitim';html=section('Zaman çizelgesi','Tarih alanını istediğiniz gibi yazabilirsiniz.',data.timeline.map((p,i)=>`<div class="timeline-card"><div class="card-title">Kayıt ${i+1}<button class="remove" data-remove-time="${i}">Sil</button></div><div class="grid">${field('Tarih','timeline.'+i+'.date',p.date)}${field('Tür (work / edu)','timeline.'+i+'.type',p.type)}${field('Başlık (TR)','timeline.'+i+'.tr',p.tr)}${field('Title (EN)','timeline.'+i+'.en',p.en)}</div>${text('Açıklama (TR)','timeline.'+i+'.trDesc',p.trDesc)}${text('Description (EN)','timeline.'+i+'.enDesc',p.enDesc)}</div>`).join('')+'<button class="add" data-add-time>+ Kayıt ekle</button>');}
$('#pageTitle').textContent=title;$('#editor').innerHTML=html;bindEditor()}
function setPath(obj,path,v){const a=path.split('.');let x=obj;for(let i=0;i<a.length-1;i++)x=x[a[i]];let value=v;if(path==='skills')value=v.split(',').map(z=>z.trim()).filter(Boolean);if(path.endsWith('.tech'))value=v.split(',').map(z=>z.trim()).filter(Boolean);x[a.at(-1)]=value}
function bindEditor(){document.querySelectorAll('[data-path]').forEach(x=>x.oninput=()=>setPath(data,x.dataset.path,x.value));document.querySelectorAll('[data-remove-project]').forEach(x=>x.onclick=()=>{data.projects.splice(+x.dataset.removeProject,1);renderEditor()});document.querySelectorAll('[data-remove-time]').forEach(x=>x.onclick=()=>{data.timeline.splice(+x.dataset.removeTime,1);renderEditor()});const addP=$('[data-add-project]');if(addP)addP.onclick=()=>{data.projects.push({name:{tr:'Yeni proje',en:'New project'},icon:'✦',tr:'Proje açıklaması',en:'Project description',tech:['Technology']});renderEditor()};const addT=$('[data-add-time]');if(addT)addT.onclick=()=>{data.timeline.push({type:'work',date:'2026',tr:'Yeni kayıt',en:'New entry',trDesc:'Açıklama',enDesc:'Description'});renderEditor()}}
$('#save').onclick=()=>{localStorage.setItem(KEY,JSON.stringify(data));const b=$('#save');b.innerHTML='Kaydedildi <b>✓</b>';setTimeout(()=>b.innerHTML='Değişiklikleri kaydet <b>✓</b>',1500)};renderEditor();

