window.SEA_DEFAULT = {
  profile: {
    name: 'Samet Erez Atmaca', initials: 'SEA', role: { tr: 'Yapay Zeka & Mobil Geliştirici', en: 'AI & Mobile Developer' },
    intro: { tr: 'Yapay zeka ve mobil teknolojiler üzerine çalışan, kullanıcı odaklı çözümler geliştiren bir geliştiriciyim.', en: 'I am a developer focused on AI and mobile technologies, building user-centric solutions.' },
    photo: 'https://sameterezatmaca.com/photo.jpg', logo: 'https://sameterezatmaca.com/logo.png', github: 'erezatmacaa-coder',
    email: 'info@sameterezatmaca.com', alternateEmail: 'erez.atmaca@hotmail.com'
  },
  about: { tr: ['Merhaba! Ben Samet Erez Atmaca. Yapay zeka ve mobil teknolojiler alanında tutkuyla çalışan bir yazılım geliştiriciyim. Modern yazılım araçlarıyla, kullanıcı deneyimini ön planda tutan yenilikçi çözümler üretiyorum.', 'Flutter, React, Python ve Node.js ile hem mobil hem web projeleri geliştiriyorum. Özellikle yapay zeka entegrasyonları ve konum bazlı servisler üzerine yoğunlaşıyorum.'], en: ["Hello! I'm Samet Erez Atmaca, a software developer passionate about AI and mobile technologies. I create innovative solutions that put user experience first.", 'I build mobile and web projects with Flutter, React, Python and Node.js, with a particular focus on AI integrations and location-based services.'] },
  stats: [{ n:'3+', tr:'Yıl deneyim', en:'Years experience' }, { n:'15+', tr:'Tamamlanan proje', en:'Projects delivered' }, { n:'8', tr:'Teknoloji', en:'Technologies' }, { n:'500+', tr:'GitHub katkısı', en:'GitHub contributions' }],
  skills: ['Flutter','React','Next.js','TypeScript','Tailwind CSS','Python','Node.js','FastAPI','Firebase','Git','Docker','Linux'],
  timeline: [{ type:'work', date:'2024 — Devam ediyor', tr:'Freelance Geliştirici', en:'Freelance Developer', trDesc:'Mobil uygulama ve yapay zeka projeleri geliştirme, danışmanlık.', enDesc:'Mobile app and AI project development, consulting.' }, { type:'work', date:'2023 — 2024', tr:'Jr. Yazılım Geliştirici', en:'Junior Software Developer', trDesc:'Web ve mobil projelerde frontend ve backend geliştirme.', enDesc:'Frontend and backend development for web and mobile projects.' }, { type:'edu', date:'2022 — Devam ediyor', tr:'Bilgisayar Mühendisliği', en:'Computer Engineering', trDesc:'Yapay zeka ve mobil teknolojiler odaklı lisans eğitimi.', enDesc:"Bachelor's degree focused on AI and mobile technologies." }],
  projects: [{ featured:true, name:{tr:'Locamo',en:'Locamo'}, icon:'https://sameterezatmaca.com/logo.png', tr:'Konum bazlı mobil platform. Kullanıcıların çevrelerini keşfetmelerini sağlayan, yapay zeka destekli akıllı öneriler sunan modern bir uygulama.', en:'A location-based mobile platform that helps people discover their surroundings through AI-powered recommendations.', tech:['Flutter','Firebase','Python','Google Maps API'] }, { name:{tr:'AI Asistan',en:'AI Assistant'}, icon:'✦', tr:'Doğal dil işleme ile çalışan, kullanıcılara günlük işlerinde yardımcı olan yapay zeka asistanı.', en:'An AI assistant powered by natural language processing that helps users with everyday tasks.', tech:['Python','OpenAI','FastAPI'] }, { name:{tr:'Portföy Platformu',en:'Portfolio Platform'}, icon:'◌', tr:'Modern web teknolojileri ile geliştirilmiş, dinamik ve etkileşimli portföy sitesi.', en:'A dynamic and interactive portfolio website built with modern web technologies.', tech:['Next.js','TypeScript','Framer Motion'] }]
};

